name: My first workflow
on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: new checkout
         uses: actions/checkout@v4
        - name: List and read files
         run: |
          echo "my first github-actions"
          ls -ltra
          cat README.md
        - name: Generate ASCII Artwork
          run: cowsay -f dragon "run for cover,I am a dragon...RAWR" >> dragon.txt

