# This is a basic workflow to help you get started with Actions

name: My first workflow
on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: new checkout
          uses: actions/checkout@v4
        - name: List and read files
          run: |
           echo "my first github-actions"
           ls -ltra
           cat README.md
        - name: Install cowsay
          run: sudo apt-get install cowsay -y

        - name: Generate ASCII Artwork
          run: cowsay -f ghostbusters "run for cover,I am a ghostbusters...RAWR" >> ghostbusters.txt

        - name: Test File Exists
          run: grep -i " ghostbusters" ghostbusterse.txt

        - name: Read File
          run: cat ghostbusters.txt

        - name: List Repo Files
          run: ls -ltra   
