# This is a basic workflow to help you get started with Actions

name: My first workflow
#on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: new checkout
          uses: actions/checkout@v4
        - name: list shell script
          run: ls -lrta
        
        - name: execute shell script
          run: |
            chmod +x ascii-script.sh
            ./ascii-script.sh

             
