name: My Multi job workflow
on: push

jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
        - name: new checkout
          uses: actions/checkout@v4
        - name: list shell script
          run: ls -lrta
        
        - name: execute shell script
          run: |
           sudo apt-get install cowsay -y
           cowsay -f ghostbusters "run for cover,I am a ghostbusters...RAWR" >> ghostbusters.txt
           pwd
           sleep 30
           
    test_job:
        runs-on: ubuntu-latest
        needs: build_job
        steps:
        - name: new checkout
          uses: actions/checkout@v4
        - name: list shell script
          run: ls -lrta
        
        - name: execute shell script
          run: |
            sudo apt-get install cowsay -y
            cowsay -f dragon "run for cover,I am a dragon...RAWR" >> dragon.txt
            ls -lrta
            pwd
            sleep 20
    
    deploy_job:
        runs-on: ubuntu-latest
        needs: test_job
        steps:
        - name: new checkout
          uses: actions/checkout@v4
        - name: list shell script
          run: ls -lrta
        
        - name: execute shell script
          run: |
              cd /home/runner/work/actions-1/actions-1/
              ls -la dragon* ghost*
