name: My Multi job workflow
on: push

jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
        - name: new checkout
          uses: actions/checkout@v4
        - name: list shell script
          run: ls -lrta
        
        - name: execute shell script
          run: sudo apt-get install cowsay -y

        - name: copy to file
          run:  cowsay -f ghostbusters "run for cover,I am a ghostbusters...RAWR" >> ghostbusters.txt
        
        - name: upload txt file ghost busters  
          uses: actions/upload-artifact@v4
          with:
            name: ghostbusters-text-file
            path: ghostbusters.txt # or path/to/artifact
           
    test_job:
        runs-on: ubuntu-latest
        needs: build_job
        steps:
        - name: new checkout
          uses: actions/checkout@v4
        - name: list shell script
          run: ls -lrta
        
        - name: execute shell script
          run: |
            sudo apt-get install cowsay -y
            cowsay -f dragon "run for cover,I am a dragon...RAWR" >> dragon.txt
            ls -lrta
        - name: upload txt file dragon 
          uses: actions/upload-artifact@v4
          with:
            name: dragon-text-file
            path: dragon.txt # or path/to/artifact

        
    
    deploy_job:
        runs-on: ubuntu-latest
        needs: test_job
        steps:
        - name: new checkout
          uses: actions/checkout@v4
        - name: list shell script
          run: ls -lrta
        
        - name: download txt file dragon 
          uses: actions/download-artifact@v4
          with:
            name: dragon-text-file
          with:
            name: ghostbusters-text-file
          
